name: Code checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4.1.4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true -B

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4.1.4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test -B


  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4.1.4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"

      - name: Install packages for python
        run: |
          python -m pip install lxml
          python -m pip install tabulate
      - name: Run checkstyle linter
        run: python tools/linter.py